# Generated by Django 3.1.7 on 2021-03-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuttigraphql', '0003_auto_20210312_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AdUser',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
    ]
