# Generated by Django 3.1.7 on 2021-03-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuttigraphql', '0004_auto_20210312_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuttigraphql.aduser'),
        ),
    ]
