# Generated by Django 3.1.7 on 2021-03-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuttigraphql', '0006_auto_20210317_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, default='bla', null=True),
        ),
    ]
