# Generated by Django 3.1.7 on 2021-03-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuttigraphql', '0011_auto_20210318_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
