# Generated by Django 3.1.7 on 2021-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuttigraphql', '0013_auto_20210319_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='nr',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
