# Generated by Django 3.1.7 on 2021-03-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuttigraphql', '0014_auto_20210321_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='nr',
            field=models.IntegerField(blank=True),
        ),
    ]
